[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/todayMatches"
  to = "/.netlify/functions/matches"
  status = 200

[[redirects]]
  from = "/api/liveMatches"
  to = "/.netlify/functions/liveMatches"
  status = 200
